// =========================================================
// AVATAR EXPRESSION SCHEMA & ATTRIBUTE DEFINITIONS
// =========================================================

export const EXPRESSION_SCHEMA = {
  // 1. EMOTIONS
  Emotion: {
    happy: {
      label: 'Happy',
      emoji: '😊',
      face: { eyeStyle: 'smile', mouthStyle: 'smile' },
      headClass: 'head-cheerful-bob',
      gesture: 'wave',
      voice: { pitch: 1.15, rate: 1.05, volume: 1.0 },
    },
    cheerful: {
      label: 'Cheerful',
      emoji: '😄',
      face: { eyeStyle: 'smile', mouthStyle: 'laugh' },
      headClass: 'head-cheerful-bob',
      gesture: 'cheer',
      voice: { pitch: 1.2, rate: 1.1, volume: 1.0 },
    },
    excited: {
      label: 'Excited',
      emoji: '🤩',
      face: { eyeStyle: 'smile', mouthStyle: 'laugh' },
      headClass: 'head-excited-bounce',
      gesture: 'cheer',
      voice: { pitch: 1.35, rate: 1.25, volume: 1.0 },
    },
    excitedly: {
      label: 'Excitedly',
      emoji: '🎉',
      face: { eyeStyle: 'smile', mouthStyle: 'laugh' },
      headClass: 'head-excited-bounce',
      gesture: 'cheer',
      voice: { pitch: 1.35, rate: 1.25, volume: 1.0 },
    },
    joyful: {
      label: 'Joyful',
      emoji: '✨',
      face: { eyeStyle: 'smile', mouthStyle: 'laugh' },
      headClass: 'head-cheerful-bob',
      gesture: 'cheer',
      voice: { pitch: 1.25, rate: 1.1, volume: 1.0 },
    },
    content: {
      label: 'Content',
      emoji: '😌',
      face: { eyeStyle: 'oval', mouthStyle: 'smile' },
      headClass: 'head-gentle-nod',
      gesture: 'rest',
      voice: { pitch: 1.0, rate: 0.95, volume: 0.9 },
    },
    calm: {
      label: 'Calm',
      emoji: '🧘',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-calm',
      gesture: 'rest',
      voice: { pitch: 0.95, rate: 0.9, volume: 0.85 },
    },
    peaceful: {
      label: 'Peaceful',
      emoji: '🕊️',
      face: { eyeStyle: 'smile', mouthStyle: 'peace' },
      headClass: 'head-calm',
      gesture: 'rest',
      voice: { pitch: 0.95, rate: 0.88, volume: 0.8 },
    },
    sad: {
      label: 'Sad',
      emoji: '😢',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-sad-droop',
      gesture: 'rest',
      voice: { pitch: 0.82, rate: 0.85, volume: 0.75 },
    },
    crying: {
      label: 'Crying',
      emoji: '😭',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-sad-droop',
      gesture: 'rest',
      soundPrefix: '*sniffles*',
      voice: { pitch: 0.8, rate: 0.8, volume: 0.7 },
    },
    angry: {
      label: 'Angry',
      emoji: '😠',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-angry-shake',
      gesture: 'rest',
      voice: { pitch: 0.85, rate: 1.15, volume: 1.0 },
    },
    furious: {
      label: 'Furious',
      emoji: '😡',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-angry-shake',
      gesture: 'rest',
      voice: { pitch: 0.8, rate: 1.25, volume: 1.0 },
    },
    afraid: {
      label: 'Afraid',
      emoji: '😨',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-afraid-shiver',
      gesture: 'rest',
      voice: { pitch: 1.25, rate: 1.2, volume: 0.85 },
    },
    nervous: {
      label: 'Nervous',
      emoji: '😰',
      face: { eyeStyle: 'circle', mouthStyle: 'smile' },
      headClass: 'head-afraid-shiver',
      gesture: 'thinking',
      voice: { pitch: 1.2, rate: 1.15, volume: 0.85 },
    },
    surprised: {
      label: 'Surprised',
      emoji: '😲',
      face: { eyeStyle: 'circle', mouthStyle: 'laugh' },
      headClass: 'head-surprised-snap',
      gesture: 'cheer',
      voice: { pitch: 1.35, rate: 1.15, volume: 1.0 },
    },
    confused: {
      label: 'Confused',
      emoji: '🤨',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-confused-tilt',
      gesture: 'thinking',
      voice: { pitch: 1.1, rate: 0.92, volume: 0.9 },
    },
    curious: {
      label: 'Curious',
      emoji: '🧐',
      face: { eyeStyle: 'circle', mouthStyle: 'smile' },
      headClass: 'head-confused-tilt',
      gesture: 'thinking',
      voice: { pitch: 1.15, rate: 1.0, volume: 0.95 },
    },
    bored: {
      label: 'Bored',
      emoji: '🥱',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-sad-droop',
      gesture: 'rest',
      voice: { pitch: 0.85, rate: 0.85, volume: 0.8 },
    },
    proud: {
      label: 'Proud',
      emoji: '😎',
      face: { eyeStyle: 'smile', mouthStyle: 'smile' },
      headClass: 'head-gentle-nod',
      gesture: 'wave',
      voice: { pitch: 1.05, rate: 1.0, volume: 1.0 },
    },
    loving: {
      label: 'Loving',
      emoji: '🥰',
      face: { eyeStyle: 'smile', mouthStyle: 'smile' },
      headClass: 'head-cheerful-bob',
      gesture: 'wave',
      voice: { pitch: 1.15, rate: 0.92, volume: 0.9 },
    },
  },

  // 2. COGNITIVE (Thinking, Reasoning, LLM states)
  Cognitive: {
    thinking: {
      label: 'Thinking',
      emoji: '🤔',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-thinking-tilt',
      gesture: 'thinking',
      voice: { pitch: 0.95, rate: 0.9, volume: 0.9 },
    },
    thoughtfully: {
      label: 'Thoughtfully',
      emoji: '💭',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-thinking-tilt',
      gesture: 'thinking',
      voice: { pitch: 0.95, rate: 0.88, volume: 0.88 },
    },
    pondering: {
      label: 'Pondering',
      emoji: '🧐',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-thinking-tilt',
      gesture: 'thinking',
      voice: { pitch: 0.92, rate: 0.85, volume: 0.85 },
    },
    considering: {
      label: 'Considering',
      emoji: '🧠',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-thinking-tilt',
      gesture: 'thinking',
      voice: { pitch: 0.96, rate: 0.92, volume: 0.9 },
    },
    realizing: {
      label: 'Realizing',
      emoji: '💡',
      face: { eyeStyle: 'circle', mouthStyle: 'laugh' },
      headClass: 'head-surprised-snap',
      gesture: 'wave',
      voice: { pitch: 1.25, rate: 1.15, volume: 1.0 },
    },
    remembering: {
      label: 'Remembering',
      emoji: '🧩',
      face: { eyeStyle: 'oval', mouthStyle: 'smile' },
      headClass: 'head-thinking-tilt',
      gesture: 'thinking',
      voice: { pitch: 1.05, rate: 0.95, volume: 0.95 },
    },
    uncertain: {
      label: 'Uncertain',
      emoji: '🤷',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-confused-tilt',
      gesture: 'thinking',
      voice: { pitch: 1.12, rate: 0.88, volume: 0.88 },
    },
    unsure: {
      label: 'Unsure',
      emoji: '❓',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-confused-tilt',
      gesture: 'thinking',
      voice: { pitch: 1.1, rate: 0.88, volume: 0.88 },
    },
    concentrating: {
      label: 'Concentrating',
      emoji: '🎯',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-thinking-tilt',
      gesture: 'thinking',
      voice: { pitch: 0.95, rate: 0.92, volume: 0.95 },
    },
  },

  // 3. DELIVERY (Volume & Tone)
  Delivery: {
    whispers: {
      label: 'Whispers',
      emoji: '🤫',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-whisper-in',
      gesture: 'thinking',
      voice: { pitch: 1.1, rate: 0.9, volume: 0.35 },
    },
    softly: {
      label: 'Softly',
      emoji: '🌸',
      face: { eyeStyle: 'smile', mouthStyle: 'peace' },
      headClass: 'head-gentle-nod',
      gesture: 'rest',
      voice: { pitch: 1.05, rate: 0.9, volume: 0.55 },
    },
    quietly: {
      label: 'Quietly',
      emoji: '🔈',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-calm',
      gesture: 'rest',
      voice: { pitch: 0.95, rate: 0.88, volume: 0.45 },
    },
    loudly: {
      label: 'Loudly',
      emoji: '📢',
      face: { eyeStyle: 'circle', mouthStyle: 'laugh' },
      headClass: 'head-excited-bounce',
      gesture: 'cheer',
      voice: { pitch: 1.25, rate: 1.15, volume: 1.0 },
    },
    shouting: {
      label: 'Shouting',
      emoji: '🗣️',
      face: { eyeStyle: 'circle', mouthStyle: 'laugh' },
      headClass: 'head-excited-bounce',
      gesture: 'cheer',
      voice: { pitch: 1.3, rate: 1.2, volume: 1.0 },
    },
    confidently: {
      label: 'Confidently',
      emoji: '💪',
      face: { eyeStyle: 'smile', mouthStyle: 'smile' },
      headClass: 'head-gentle-nod',
      gesture: 'wave',
      voice: { pitch: 1.05, rate: 1.05, volume: 1.0 },
    },
    seriously: {
      label: 'Seriously',
      emoji: '💼',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-gentle-nod',
      gesture: 'rest',
      voice: { pitch: 0.9, rate: 0.95, volume: 0.95 },
    },
    casually: {
      label: 'Casually',
      emoji: '☕',
      face: { eyeStyle: 'oval', mouthStyle: 'smile' },
      headClass: 'head-calm',
      gesture: 'wave',
      voice: { pitch: 1.0, rate: 1.0, volume: 0.95 },
    },
  },

  // 4. PACE / SPEED
  Pace: {
    very_slow: {
      label: 'Very Slow',
      emoji: '🐢',
      voice: { rate: 0.65 },
    },
    slowly: {
      label: 'Slowly',
      emoji: '⏳',
      voice: { rate: 0.8 },
    },
    normal: {
      label: 'Normal Pace',
      emoji: '⏱️',
      voice: { rate: 1.0 },
    },
    fast: {
      label: 'Fast',
      emoji: '⚡',
      voice: { rate: 1.3 },
    },
    very_fast: {
      label: 'Very Fast',
      emoji: '🚀',
      voice: { rate: 1.55 },
    },
  },

  // 5. ATTITUDE & PERSONALITY
  Attitude: {
    sarcastic: {
      label: 'Sarcastic',
      emoji: '😏',
      face: { eyeStyle: 'oval', mouthStyle: 'smile' },
      headClass: 'head-confused-tilt',
      gesture: 'thinking',
      voice: { pitch: 0.9, rate: 0.92, volume: 0.95 },
    },
    mischievous: {
      label: 'Mischievous',
      emoji: '😈',
      face: { eyeStyle: 'smile', mouthStyle: 'smile' },
      headClass: 'head-cheerful-bob',
      gesture: 'wave',
      voice: { pitch: 1.15, rate: 1.1, volume: 0.95 },
    },
    playful: {
      label: 'Playful',
      emoji: '🎈',
      face: { eyeStyle: 'smile', mouthStyle: 'laugh' },
      headClass: 'head-cheerful-bob',
      gesture: 'cheer',
      voice: { pitch: 1.2, rate: 1.12, volume: 1.0 },
    },
    skeptical: {
      label: 'Skeptical',
      emoji: '🤨',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-confused-tilt',
      gesture: 'thinking',
      voice: { pitch: 0.92, rate: 0.9, volume: 0.9 },
    },
    deadpan: {
      label: 'Deadpan',
      emoji: '😐',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-calm',
      gesture: 'rest',
      voice: { pitch: 0.88, rate: 0.95, volume: 0.85 },
    },
  },

  // 6. NON-VERBAL EXPRESSIONS
  NonVerbal: {
    laughs: {
      label: 'Laughs',
      emoji: '🤣',
      face: { eyeStyle: 'smile', mouthStyle: 'laugh' },
      headClass: 'head-excited-bounce',
      gesture: 'cheer',
      soundPrefix: 'Haha! ',
      voice: { pitch: 1.3, rate: 1.2 },
    },
    giggles: {
      label: 'Giggles',
      emoji: '🤭',
      face: { eyeStyle: 'smile', mouthStyle: 'smile' },
      headClass: 'head-cheerful-bob',
      gesture: 'thinking',
      soundPrefix: 'Hehe! ',
      voice: { pitch: 1.35, rate: 1.25 },
    },
    sighs: {
      label: 'Sighs',
      emoji: '😮‍💨',
      face: { eyeStyle: 'oval', mouthStyle: 'peace' },
      headClass: 'head-sad-droop',
      gesture: 'rest',
      soundPrefix: '*Sigh*... ',
      voice: { pitch: 0.8, rate: 0.75 },
    },
    gasps: {
      label: 'Gasps',
      emoji: '😱',
      face: { eyeStyle: 'circle', mouthStyle: 'laugh' },
      headClass: 'head-surprised-snap',
      gesture: 'cheer',
      soundPrefix: '*Gasp!* ',
      voice: { pitch: 1.4, rate: 1.2 },
    },
    yawns: {
      label: 'Yawns',
      emoji: '🥱',
      face: { eyeStyle: 'oval', mouthStyle: 'laugh' },
      headClass: 'head-sad-droop',
      gesture: 'rest',
      soundPrefix: '*Yawwwn*... ',
      voice: { pitch: 0.75, rate: 0.7 },
    },
  },

  // 7. GESTURES & HAND POSES
  Gestures: {
    say_hi: {
      label: 'Say Hi (Right Wave)',
      emoji: '🙋‍♂️',
      gesture: 'say_hi',
      headClass: 'head-cheerful-bob',
      voice: { pitch: 1.15, rate: 1.05, volume: 1.0 },
    },
    hands_up: {
      label: 'Hands Up',
      emoji: '🙌',
      gesture: 'hands_up',
      headClass: 'head-excited-bounce',
      voice: { pitch: 1.25, rate: 1.1, volume: 1.0 },
    },
    hands_down: {
      label: 'Hands Down',
      emoji: '🧘',
      gesture: 'hands_down',
      headClass: 'head-calm',
      voice: { pitch: 0.95, rate: 0.95, volume: 0.9 },
    },
    wave_right: {
      label: 'Wave Right',
      emoji: '👋',
      gesture: 'wave_right',
      headClass: 'head-cheerful-bob',
      voice: { pitch: 1.1, rate: 1.05, volume: 1.0 },
    },
    wave_left: {
      label: 'Wave Left',
      emoji: '🙋‍♀️',
      gesture: 'wave_left',
      headClass: 'head-cheerful-bob',
      voice: { pitch: 1.1, rate: 1.05, volume: 1.0 },
    },
    cheer: {
      label: 'Cheer Both',
      emoji: '🎉',
      gesture: 'cheer',
      headClass: 'head-excited-bounce',
      voice: { pitch: 1.3, rate: 1.2, volume: 1.0 },
    },
    thinking_pose: {
      label: 'Thinking Pose',
      emoji: '🤔',
      gesture: 'thinking',
      headClass: 'head-thinking-tilt',
      voice: { pitch: 0.95, rate: 0.9, volume: 0.9 },
    },
  },

  // 8. CHARACTER / STYLE TRANSFORMATIONS
  Style: {
    robot: {
      label: 'Robot',
      emoji: '🤖',
      face: { eyeStyle: 'circle', mouthStyle: 'peace' },
      headClass: 'head-calm',
      gesture: 'rest',
      voice: { pitch: 0.7, rate: 0.95 },
    },
    cartoon: {
      label: 'Cartoon',
      emoji: '🎨',
      face: { eyeStyle: 'smile', mouthStyle: 'laugh' },
      headClass: 'head-excited-bounce',
      gesture: 'cheer',
      voice: { pitch: 1.45, rate: 1.2 },
    },
    storyteller: {
      label: 'Storyteller',
      emoji: '📖',
      face: { eyeStyle: 'smile', mouthStyle: 'smile' },
      headClass: 'head-gentle-nod',
      gesture: 'wave',
      voice: { pitch: 1.05, rate: 0.9 },
    },
  },
};

// PRESET MULTI-TAG DEMO SCENARIOS
export const PRESET_SCENARIOS = [
  {
    title: 'Thinking ➔ Realizing',
    tag: 'Thought Cloud + Lightbulb',
    text: '[thinking, thinking_pose] Hmm, let me work through that... [realizing, excitedly, say_hi] Ah! I see exactly what happened!',
  },
  {
    title: 'Hands Up Celebration',
    tag: 'Both Hands Up 🙌',
    text: '[cheerful, hands_up] Hey! Two hands up! We finally did it and it looks absolutely amazing!',
  },
  {
    title: 'Say Hi (Right Wave)',
    tag: 'One Hand Up 🙋‍♂️',
    text: '[cheerful, say_hi] Hi there! It is wonderful to meet you today! 👋',
  },
  {
    title: 'Unsure & Curious',
    tag: 'Question Mark ❓',
    text: '[unsure, thinking] Hmm... I am not entirely sure about that, let me double check.',
  },
  {
    title: 'Playful & Joyful',
    tag: 'Musical Notes 🎶',
    text: '[playful, cheer] Tra-la-la! Having so much fun with all these expressions and gestures!',
  },
  {
    title: 'Hands Down & Calm',
    tag: 'Relaxed Pose 🧘',
    text: '[calm, hands_down] Take a relaxed breath. Both hands resting peacefully down.',
  },
];
